module.exports = {
    addSituationAPI: 'https://script.google.com/macros/s/***/exec',
    backSituationAPI: 'https://script.google.com/macros/s/***/exec',
    exeSituationAPI: 'https://script.google.com/macros/s/***/exec',
    checkSituationNOAPI:'https://script.google.com/macros/s/***/exec',
    getSituationAPI: 'https://script.google.com/macros/s/***/exec',
    getSituationStatusList: 'https://script.google.com/***/exec',
    logSheetAPI: 'https://script.google.com/macros/s/***/exec',
    formURL: 'https://docs.google.com/spreadsheets/d/***/edit#gid=835926508',
    channelId: 'yourChannelID',
    channelSecret: 'yourChannelSecret',
    channelAccessToken: 'yourChannelAccessToken',
    addGroupIDAPI: 'https://script.google.com/macros/s/***/exec',
    deleteGroupIDAPI: 'https://script.google.com/macros/s/***/exec',
    getGroupIDAPI: 'https://script.google.com/macros/s/***/exec',
};